version: '3.8'
networks:
  backend:
    name: app
    driver: bridge
volumes:
  postgres_data:
    driver: local
services:
  app:
    image: 'document-management:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_db
      - keycloak
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_db:5432/document_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    networks:
      - backend
  postgresql_db:
    image: 'postgres'
    container_name: postgresql_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=document_management
    ports:
      - "5432:5432"
    networks:
      - backend

  postgres:
    image: postgres
    container_name: postgresql_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - backend
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - "9990:8080"
    depends_on:
      - postgres
    networks:
      - backend
