server:
  port: 8081
  servlet:
    contextPath: /api/document-management

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/document_management?useUnicode=yes&characterEncoding=UTF-8
    username: postgres
    password: postgres
    continue-on-error: false
  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include:
            - health
            - info
            - metrics
            - prometheus
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          batch-size: 400
          lob:
            non_contextual_creation: true
        format_sql: false
        order_inserts: true
    show-sql: false
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    enabled: false
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: always
# ========= Logging ========== #
#logging:
#  level:
#    root: ERROR
#    com:
#      example:
#        documentmanagement: DEBUG
# ========= Swagger ========== #
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# ========= Keycloak ========== #
keycloak:
  enabled: true
  realm: realm
  auth-server-url: http://127.0.0.1:9990/auth/
  resource: document-client
  bearer-only: true
  use-resource-role-mappings: true
  cors-allowed-methods: "POST, PUT, DELETE, GET, OPTIONS, PATCH"
  cors-exposed-headers: "WWW-Authenticate,accept,content-type"
  credentials:
    secret: j3ykqQnaQQ5UNMMrl2hR9zTlGMGyVbC8
  securityConstraints:
    - authRoles:
        - document-auth-role
      securityCollections:
        - name: Document-Management
          patterns:
            - /*
